- name: Instalar Node.js e TDS-CLI
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Versão estável do Node

      - name: Instalar TDS-CLI via NPM
        run: |
          npm install -g @totvs/tds-cli
          # O comando passa a ser 'tds-cli' diretamente no PATH

      - name: Compilar Fontes no Protheus Remoto
        run: |
          tds-cli compile \
            --server ${{ secrets.PROTHEUS_SERVER }} \
            --port 1234 \
            --environment ${{ secrets.PROTHEUS_ENV }} \
            --user ${{ secrets.PROTHEUS_USER }} \
            --password "${{ secrets.PROTHEUS_PASS }}" \
            --program "${{ github.workspace }}/src" \
            --include "${{ github.workspace }}/includes" \
            --save-logs
