name: "Compilacao Protheus 2310"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout do Codigo"
        uses: actions/checkout@v4

      - name: "Configurar Permissoes e Compilar"
        run: |
          # 1. Ajustado para o nome real do ficheiro no seu repo: 'advpls'
          chmod +x ./bin/advpls
          
          # 2. Executa a compilação usando o binário correto
          ./bin/advpls compile \
            --server ${{ secrets.PROTHEUS_SERVER }} \
            --port 1234 \
            --environment ${{ secrets.PROTHEUS_ENV }} \
            --user ${{ secrets.PROTHEUS_USER }} \
            --password "${{ secrets.PROTHEUS_PASS }}" \
            --program "${{ github.workspace }}/src" \
            --include "${{ github.workspace }}/includes" \
            --save-logs